---
- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - aptitude
    - ntp
    - ntpdate
    - python-pip
  tags:
    - apt
    - ntp
