---
- name: Install pip dependencies for running the unit and functional tests.
  pip:
    requirements: "{{ test_pip_requirements }}"
  tags:
    - pip

- name: Install testing package dependencies.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ test_apt_dependencies }}"
  tags:
    - apt

- name: Set DISPLAY environment variable for xvfb.
  copy:
    src: xvfb_display.sh
    dest: /etc/profile.d/xvfb_display.sh
    owner: root
    mode: "0444"
  tags:
    - xvfb
    - environment
    - permissions
